name: Pipeline CI/CD ÉcoShop Deploy FTP

on:
  push:
    branches: ["force_deploy"]
  pull_request:
    branches: ["force_deploy"]

jobs:

  # ==========================================
  # DÉPLOIEMENT PROD (Serveur SFTP)
  # ==========================================
  deploy-to-production:
    name: Déploiement Production Souveraine (Alwaysdata)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Déploiement Production SFTP Sovereign
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.SFTP_SERVER }}
          username: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PASSWORD }}
          port: 22
          local-dir: ./
          server-dir: ~/www/